name: Secret Scan

on:
  push:
    branches:
      - main
      - test/secret-detect
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest \
          | grep "browser_download_url.*linux-amd64.tar.gz" \
          | cut -d '"' -f 4 \
          | wget -qi -
          tar -xzf gitleaks-*-linux-amd64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks secret scan
        run: |
          gitleaks detect --source . --no-git -v
