name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for scanning entire history if needed

      # Basic test step (so you can see pipeline passing/failing)
      - name: Run sample build check
        run: |
          echo "✅ CI pipeline running for branch: $GITHUB_REF"
          echo "Simulating build/test step"
      
      # Install Gitleaks for secret scanning
      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz
          tar -xvzf gitleaks-linux-amd64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      # Run Gitleaks scan
      - name: Run Gitleaks secret scan
        run: |
          echo "🔍 Scanning for secrets..."
          gitleaks detect --source . --no-git -v
