name: CI Pipeline with Gitleaks

on:
  push:
    branches:
      - trigger-ci
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks secret scan
        uses: zricethezav/gitleaks-action@v2
