name: Secret Scan

on:
  pull_request:
    branches:
      - main

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout full PR history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Gitleaks manually
      - name: Install Gitleaks
        run: |
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz | tar -xz
          sudo mv gitleaks /usr/local/bin/

      # Run Gitleaks scan on the entire repo
      - name: Run Gitleaks
        run: |
          gitleaks detect --source . --redact --exit-code=1
